# Generated by Django 5.1 on 2024-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomikuvzpevnik', '0003_alter_songdata_favorite_alter_songdata_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='dark_theme',
            field=models.BooleanField(default=False),
        ),
    ]
