# Generated by Django 5.1 on 2024-10-23 21:45

import tomikuvzpevnik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomikuvzpevnik', '0004_userpreferences_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdata',
            name='transpose',
            field=models.IntegerField(default=0, validators=[tomikuvzpevnik.models.validate_capo]),
        ),
    ]
