# Generated by Django 5.1 on 2024-11-10 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomikuvzpevnik', '0005_songdata_transpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 10, 32, 33, 808782)),
        ),
        migrations.AddField(
            model_name='song',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
