# Generated by Django 5.1 on 2025-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomikuvzpevnik', '0006_song_created_song_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
