# Generated by Django 5.1 on 2025-05-24 10:27

import tomikuvzpevnik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomikuvzpevnik', '0007_alter_song_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='capo',
            field=models.IntegerField(default=0, validators=[tomikuvzpevnik.models.validate_capo]),
        ),
    ]
